---
# copy set of patches used to setup Contrail VM
- name: install fixtures
  pip: 
    name: "{{ item }}"
  become: yes
  become_method: sudo
  with_items:
    - 'fixtures'

- name: copy contrail_patches
  copy:
    src: ../files/contrail_patches
    dest: ~/devstack/contrail_patches
 
- name: copy plugin.patch
  copy:
    src: ../files/plugin.patch
    dest: ~/devstack/plugin.patch

- name: copy contrail_config.patch
  copy:
    src: ../files/contrail_config.patch
    dest: ~/devstack/contrail_config.patch
