---
# install required dependencies 
- name: update apt cache
  command: apt update
  become: yes
  become_method: sudo

- name: install python-apt, pip & setuptools
  command: apt install {{ item }} -y 
  with_items:
    - "python-apt"
    - "python-setuptools"
    - "python-pip"
  become: yes
  become_method: sudo

- name: install git
  apt:
    name: "{{ item }}"
    update_cache: yes
    cache_valid_time: 3600
  with_items:
    - "git"
  become: yes
  become_method: sudo

- name: (hack) install devstack dependencies which will be replaced with those from devstack requirements.txt
  command: pip install {{ item }}
  become: yes
  become_method: sudo
  with_items:
    - 'pytz'
    - 'iso8601'
    - 'cmd2'
    - 'netifaces'
    - 'monotonic'
    - 'wrapt'
    - 'rfc3986'
  when: ansible_distribution_release == 'xenial'
