---
# install required dependencies 
- name: install python-apt, pip, setuptools & python-dev
  command: apt install {{ item }} -y 
  with_items:
    - "python-apt"
    - "python-setuptools"
    - "python-pip"
    - "python-dev"
  become: yes
  become_method: sudo

- name: install git
  apt:
    name: "{{ item }}"
    update_cache: yes
    cache_valid_time: 3600
  with_items:
    - "git"
  become: yes
  become_method: sudo

- name: '[hack] install devstack dependencies those will be replaced later with devstack requirements.txt'
  pip: 
    name: "{{ item }}"
  become: yes
  become_method: sudo
  with_items:
    - 'pytz'
    - 'iso8601'
    - 'cmd2'
    - 'netifaces'
    - 'monotonic'
    - 'wrapt'
    - 'rfc3986'
