# These tasks will be merged into deployment graph. Here you
# can specify new tasks for any roles, even built-in ones.

- id: contrail-mechanism-driver_role
  type: group
  role: [contrail-mechanism-driver_role]
  requires: [deploy_start]
  tasks: [contrail-mechanism-driver-deps, contrail-mechanism-driver-deployment]
  parameters:
    strategy:
      type: parallel

- id: contrail-mechanism-driver-deps
  type: puppet
  role: [contrail-mechanism-driver-for-gluon]
  version: 2.0.0
  cross-depends:
    - name: deploy_start
  cross-depended-by:
    - name: deploy_end
  parameters:
    puppet_manifest: "contraildriver-deps.pp"
    puppet_modules: "."
    timeout: 3600

- id: contrail-mechanism-driver-deployment
  type: puppet
  role: [contrail-mechanism-driver-for-gluon]
  version: 2.0.0
  cross-depends:
    - name: deploy_start
    - name: contrail-mechanism-driver-deps
  cross-depended-by:
    - name: deploy_end
  parameters:
    puppet_manifest: "contraildriver-install.pp"
    puppet_modules: "."
    timeout: 3600

#- id: fuel-plugin-example-post-deployment-sh
#  type: shell
#  role: [contrail-mechanism-driver-for-gluon]
#  version: 2.0.0
#  cross-depends:
#    - name: post_deployment_start
#  cross-depended-by:
#    - name: post_deployment_end
# #  requires: [post_deployment_start]
# #  required_for: [post_deployment_end]
#  parameters:
#    cmd: echo post_deployment_task_executed > /tmp/post_deployment
#    retries: 3
#    interval: 20
#    timeout: 180

#- id: fuel-plugin-example-pre-deployment-sh
#  type: shell
#  role: [contrail-mechanism-driver-for-gluon]
#  version: 2.0.0
#  cross-depends:
#    - name: pre_deployment_start
#  cross-depended-by:
#    - name: pre_deployment_end
# #  requires: [pre_deployment_start]
# #  required_for: [pre_deployment_end]
#  parameters:
#    cmd: echo pre_deployment_task_executed > /tmp/pre_deployment
#    retries: 3
#    interval: 20
#    timeout: 180
