---
# Copy ContrailMechanismDriver dependencies from Contrail VM
- name: create archive for vnc_api module
  command: chdir=/opt/stack/contrail/build/production/api-lib python setup.py sdist
  become: yes
  become_method: sudo
 
- name: create archive for cfgm_common module
  command: chdir=/opt/stack/contrail/build/production/config/common python setup.py sdist
  become: yes
  become_method: sudo

- name: fetch vnc_api module
  fetch:
    src: /opt/stack/contrail/build/production/api-lib/dist/vnc_api-0.1.dev0.tar.gz
    dest: files/vnc_api-0.1.dev0.tar.gz
    flat: yes
 
- name: fetch cfgm_common module
  fetch:
    src: /opt/stack/contrail/build/production/config/common/dist/cfgm_common-0.1.dev0.tar.gz
    dest: files/cfgm_common-0.1.dev0.tar.gz
    flat: yes
