---
# Copy ContrailMechanismDriver dependencies to Openstack VM
# and install them
- name: copy vnc_api && cfgm_common module
  copy:
    src: files/{{ item }}
    dest: ~/devstack/
  with_items:
    - 'vnc_api-0.1.dev0.tar.gz'
    - 'cfgm_common-0.1.dev0.tar.gz'
 
- name: install vnc_api && cfgm_common module
  shell: 'cd ~/devstack && sudo pip install {{ item }}'
  with_items:
    - 'vnc_api-0.1.dev0.tar.gz'
    - 'cfgm_common-0.1.dev0.tar.gz'

- name: clone contrail-neutron-plugin to ensure missing dependencies
  git: 
    repo: "https://github.com/Juniper/contrail-neutron-plugin.git"
    dest: ~/ 
    accept_hostkey: yes

- name: install vnc_api && cfgm_common module
  shell: 'cd ~/contrail-neutron-plugin && sudo python setup.py install'
