---
- hosts: contrail
  remote_user: ubuntu
  gather_facts: no 
  become: no
  connection: ssh

  roles:
    - { role: common }
    - { role: fetch_devstack, vm_group: contrail }
    - { role: contrail_vm }
    - { role: source_openrc }
