---
- hosts: openstack 
  remote_user: ubuntu
  gather_facts: yes 
  become: no
  connection: ssh

  roles:
    - { role: common }
    - { role: fetch_devstack, vm_group: openstack }
    - { role: openstack_vm }
    - { role: source_openrc }
